[package]
name = "listen-engine"
version = "0.1.0"
edition = "2021"
default-run = "listen-engine"

[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] }
ctor = "0.2.9"
dotenvy = "0.15.7"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.12.1", features = ["serde", "v4"] }
redis = { version = "0.23.3", features = ["tokio-comp"] }
futures-util = "0.3.31"
actix-web = { version = "4", features = ["rustls-0_23"] }
thiserror = "2.0.11"
metrics = "0.21"
metrics-exporter-prometheus = "0.12"
once_cell = "1.18"
bb8-redis = "0.20.0"
privy = { path = "../privy" }

[[bin]]
name = "listen-engine"
path = "bin/engine.rs"
